### ISSUE TITLE
iOS example app crashes during the file loading

### ISSUE THREAD

**Issue by GianlucaMancusi** [SKKbySSK/audio_engine#14]
Hello, thanks for the awesome work you are doing on this package!
I was trying to deal with the file loading on iOS Simulator but using the path retrieved by the path_provider it ends to a crash.
The extracted path is:
`"/Users/mypc/Library/Developer/CoreSimulator/Devices/FA639177-5140-4956-9F08-4317F978F65B/data/Containers/Data/Application/D1FA658E-90DC-4FB1-9660-3FE04A320B33/Documents/test1.mp3"` (is it a strange path?)

The crash happens on line 18 of AudioFileNodePlugin.swift, that is:
```
let file = try! AVAudioFile(forReading: URL(fileURLWithPath: path))
```

The error:
`
Thread 1: Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=com.apple.coreaudio.avfaudio Code=1685348671 "(null)" UserInfo={failed call=ExtAudioFileOpenURL((CFURLRef)fileURL, &_extAudioFile)}
`

Have you some ideas?

**Comment by SKKbySSK** [comment]
Hi @GianlucaMancusi 
Thanks for using this package!

Sorry, I didn't add sample mp3 files in this repository.
You should add these files to `example/assets/` manually.
- test1.mp3
- test2.mp3
- test3.mp3

Otherwise, example app will be crashed.

https://github.com/SKKbySSK/audio_graph/blob/80c12fc9c10fda5f444557468574de09d14f0bc7/example/lib/main.dart#L52-L58

**Comment by GianlucaMancusi** [comment]
Thanks for the answer @SKKbySSK, 
I have already added these files (I've tested it with 3 music mp3 files), but nothing changes. The app crashes on that line.
On Android the example app loads those 3 files without any problem.

Have you tried on an iOS Simulator?

**Comment by SKKbySSK** [comment]
Yes, I've tested on iOS13.4 iPhone 11 Pro Max simulator and it works fine.
`Code 1685348671` means [kAudioFileInvalidFileError](https://developer.apple.com/documentation/audiotoolbox/kaudiofileinvalidfileerror) on iOS.
Can you attach the mp3 files you are using?

**Comment by GianlucaMancusi** [comment]
Of course. I've tried this one (downloaded from YT).
[test1.mp3.zip](https://github.com/SKKbySSK/audio_graph/files/4457380/test1.mp3.zip)

**Comment by SKKbySSK** [comment]
Your attached file seems to have mp4a format.
Try changing its file name to test1.m4a and corresponding example code.

```
  Duration: 00:03:42.05, start: 0.000000, bitrate: 129 kb/s
    Stream #0:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
```

**Comment by GianlucaMancusi** [comment]
That's just it! Great, thank you.
